### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by nr-patel** [saurabhd336/Driver-distraction#1]
Hi,

First I am getting error at: int triangulation(cv::Mat, dlib::full_object_detection, int*)’: error: reference to ‘line’ is ambiguous
I have solved this by adding cv::line()

after successful cmake and build, I am getting error like Segmentation fault (code dumped)

Any suggestions?

**Comment by saurabhd336** [comment]
Did you copy the model.bin file from the project repo to the executable's location?

**Comment by nr-patel** [comment]
Thanks Saurabh, Yes after copying model.bin to build it is working. Earlier I have just updated the path.
